env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
overrides: []
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - react
  - filenames
  - jsx-a11y
  - simple-import-sort
rules:
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  import/prefer-default-export: 0
  no-unused-vars: 1
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  import/no-unresolved: 0
  simple-import-sort/imports: 'error'
  simple-import-sort/exports: 'error'
  react/display-name: 0
  no-console: ['warn', { allow: ['warn', 'error'] }]
  import/extensions: 0
  no-param-reassign: 0